# Generated by Django 3.1.6 on 2021-02-10 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pepowidehard', '0003_auto_20210210_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangodb',
            name='bild',
            field=models.ImageField(default='images/forkoriiii.png', upload_to='images/'),
        ),
    ]
