# Generated by Django 3.1.6 on 2021-02-18 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pepowidehard', '0005_auto_20210210_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangodb',
            name='bild',
            field=models.ImageField(default='posts/frx.png', null=True, upload_to='posts/'),
        ),
        migrations.AlterField(
            model_name='djangodb',
            name='datum',
            field=models.DateTimeField(null=True, verbose_name='date published'),
        ),
    ]
